### ISSUE TITLE
How to run parsemis?

### ISSUE THREAD

**Issue by liangyaopei** [timtadh/parsemis#1]
Hello, recently I am doing academic research about graph mining, and I need to use gSpan. I want to know how to run this repository after cloning the repository into local machine?

**Comment by timtadh** [comment]
I do not provide support for this code. If you wish to get support please contact the original authors. I do support my own graph mining system REGRAX (https://github.com/timtadh/regrax). Please cite:

> **Tim A. D. Henderson**. [Frequent Subgraph Analysis and its Software Engineering Applications](http://hackthology.com/frequent-subgraph-analysis-and-its-software-engineering-applications.html). [Case Western Reserve University](http://case.edu/). Doctoral Dissertation. 2017.

If you intend to use REGRAX for real you will want to work with me to find the best options and modes. It is NOT self explanatory.
