### ISSUE TITLE
gspan 

### ISSUE THREAD

**Issue by horvathr** [timtadh/parsemis#2]
Hello,
In de.parsemis.algorithms.gSpan,  
class  GSpanGeneration<NodeType, EdgeType> extends GenerationStep<NodeType,EdgeType> 
method 	private void searchEmbeddings(final GSpanGraph<NodeType, EdgeType> dbgraph,
	final GSpanEdge<NodeType, EdgeType> currentEdge,
	final DFSCode<NodeType, EdgeType> code, final int[] ackNodes,
	final int[] usedNodes, final BitSet freeEdges) 

the for-loop  "for (int i = me.getDegree(node) - 1; i >= 0; --i)" seems to go into never ending loop under the following input, see below.
The condition is when me.getDegree(node) = 14, the if part of the following if-then-else statement "call{}" is called until 'i' in the for loop reaches '1' and then searchEmbeddings is called. This process repeats itself infinitely.

if (currentEdge.next == null) {							
	call(code, tenv.getHPEmbedding(code, dbgraph,ackNodes, freeEdges));
} else {
	searchEmbeddings(dbgraph, currentEdge.next, code,ackNodes, usedNodes, freeEdges);
}

I am running with java -Xms171072M -Xmx171072M  JVM heap size. 

If you can provide me with any guidance, I truly will appreciate it.

Thank you.

Input argument
args[0]=--graphFile=input.lg
args[1]=--outputFile=output.lg
args[2]=--minimumFrequency=2
args[3]=--maximumFrequency=2000
args[4]=--minimumNodeCount=5
args[5]=--maximumNodeCount=20
args[6]=--minimumEdgeCount=20
args[7]=--maximumEdgeCount=10
args[8]=--findPathsOnly=false
args[9]=--connectedFragments=true
args[10]=--algorithm=gspan
args[11]=--closeGraph=false
args[12]=--subdue=false
args[13]=--zaretsky=false
args[14]=--distribution=threads
args[15]=--threads=5
args[16]=--memoryStatistics=false
args[17]=--naturalOrdered=none
args[18]=--reverseOrdered=none
args[19]=--storeEmbeddings=false
args[20]=--swapFile=/home/jggmb/SubstructureDiscovery/swap.txt
args[21]=--memoryStatistics=false

INPUT TREE (input.lg)
t # tt0
v 0 65
v 1 66
v 2 66
v 3 66
v 4 66
v 5 66
v 6 66
v 7 66
v 8 66
v 9 66
v 10 66
v 11 66
v 12 66
v 13 66
v 14 66
v 15 66
v 16 66
e 0 1 S
e 0 2 A
e 0 3 A
e 3 4 A
e 3 5 A
e 3 6 A
e 3 7 A
e 3 8 A
e 3 9 A
e 3 10 A
e 3 11 A
e 3 12 A
e 3 13 A
e 3 14 A
e 3 15 A
e 3 16 A
t # tt1
v 0 65
v 1 30
v 2 30
v 3 66
v 4 66
v 5 66
v 6 66
v 7 66
v 8 66
v 9 66
v 10 66
v 11 66
v 12 66
v 13 66
v 14 66
v 15 66
v 16 66
e 0 1 S
e 0 2 A
e 0 3 A
e 3 4 A
e 3 5 A
e 3 6 A
e 3 7 A
e 3 8 A
e 3 9 A
e 3 10 A
e 3 11 A
e 3 12 A
e 3 13 A
e 3 14 A
e 3 15 A
e 3 16 A"

**Comment by timtadh** [comment]
For support for this tool contact the original authors: https://www2.cs.fau.de/EN/research/zold/ParSeMiS/index.html

My mining platform is https://github.com/timtadh/regrax described in https://hackthology.com/frequent-subgraph-analysis-and-its-software-engineering-applications.html (see chapter 2 in the PDF). If you want to use REGRAX let me know and I will consult with you on the proper configuration. It is not self explanatory.

**Comment by horvathr** [comment]
I apologize for the late reply. Thank you very much for your support. I
will contact the original author.
