### ISSUE TITLE
Parsemis does not implement CloseGraph algorithm

### ISSUE THREAD

**Issue by shaulz** [timtadh/parsemis#3]
Parsemis does not implement CloseGraph algorithm as described in "CloseGraph: Mining Closed Frequent Graph Patterns" by  Xifeng Yan and Jiawei Han.

The  --closeGraph=true option runs gSpan and then filters gSpan results to find close graphs.

Parsemis implementation adds extra time to gSpan by applying that filter.
If CloseGraph algorithm was implemented, it would achieve same result by one order of magnitude faster.

**Comment by timtadh** [comment]
Please contact the original authors for support.
